# Generated by Django 5.2.13 on 2026-04-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profile_avata_url_profile_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avata_url',
        ),
    ]
